spring:
  application:    name: account
  config:
     import: optional:configserver:http://localhost:8888
       
#  cloud:#    config:#      uri: http://localhost:8888

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics

    