server:  
  port: 8888
  
spring:  
  application:
    name: configserver  
    
  profiles:    active: native
    
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Users/jmagalmo/Documents/proyectos/bootCamp-microservice/springConfigServer
          
#  cloud:
#    config:
#      server:          
#       git:
#          uri: https://github.com/jhoss64gEveris/files-config-server.git
#         search-paths:
#          username: jhoss64gEveris
#          password: systeM64@
#          clone-on-start: true
          