version: '3.8'
services:
  eureka-server:
    image: eureka 
    restart: always
    container_name: eureka
    hostname: eureka-server
    ports:
      - '8761:8761'
    networks:
      - 'banking-network'
  config-server:
    image: config 
    restart: always
    container_name: config
    hostname: config-server
    ports:
      - '8888:8888'
    networks:
      - 'banking-network'
  zuul-service:
    image: gateway 
    restart: always
    container_name: gateway
    ports:
      - '7001:7001'
    networks:
      - 'banking-network'
  account:
    image: account 
    restart: always
    container_name: account-microservice
    networks:
      - 'banking-network'
  db-account: #replicar configuracion para otras bd de la misma imagen
    image: mongo
    restart: always
    container_name: mongodb_account #cambia el prefijo por el nombre del microservicio
    hostname: mongodb-server
    networks:
      - 'banking-network'
    ports:
      - '1255:27017' #los puertos van a ir en secuencia desde la 1255 en adelante
networks:
  banking-network: 