spring:
  application:
    name: eureka-server
 
#Tomcat Embedded Server Configuration
server: 
  port: 8761
 
#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false #tener en cuenta para cuando se despliegue en docker
    fetchRegistry: false
  server:    enable-self-preservation: true